// <auto-generated />
using System;
using HubGruposEstudo.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HubGruposEstudo.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524095752_AdicionarDominioCompleto")]
    partial class AdicionarDominioCompleto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HubGruposEstudo.Domain.Entities.Conquista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Criterio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("conquistas", (string)null);
                });

            modelBuilder.Entity("HubGruposEstudo.Domain.Entities.ConquistaUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConquistaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataObtida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConquistaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("conquistas_usuarios", (string)null);
                });

            modelBuilder.Entity("HubGruposEstudo.Domain.Entities.Etapa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("DuracaoEstimadaMin")
                        .HasColumnType("integer");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TrilhaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrilhaId");

                    b.ToTable("etapas", (string)null);
                });

            modelBuilder.Entity("HubGruposEstudo.Domain.Entities.Habilidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("habilidades", (string)null);
                });

            modelBuilder.Entity("HubGruposEstudo.Domain.Entities.Inscricao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Concluida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EtapaAtual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<Guid>("TrilhaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrilhaId");

                    b.HasIndex("UsuarioId", "TrilhaId")
                        .IsUnique();

                    b.ToTable("inscricoes", (string)null);
                });

            modelBuilder.Entity("HubGruposEstudo.Domain.Entities.Trilha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CriadorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("HabilidadeId")
                        .HasColumnType("uuid");

                    b.Property<string>("NivelDificuldade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CriadorId");

                    b.HasIndex("HabilidadeId");

                    b.ToTable("trilhas", (string)null);
                });

            modelBuilder.Entity("HubGruposEstudo.Domain.Entities.Troca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HabilidadeAId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HabilidadeBId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TrilhaAId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrilhaBId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioAId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioBId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HabilidadeAId");

                    b.HasIndex("HabilidadeBId");

                    b.HasIndex("TrilhaAId");

                    b.HasIndex("TrilhaBId");

                    b.HasIndex("UsuarioAId");

                    b.HasIndex("UsuarioBId");

                    b.ToTable("trocas", (string)null);
                });

            modelBuilder.Entity("HubGruposEstudo.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Nivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Xp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("HubGruposEstudo.Domain.Entities.UsuarioHabilidade", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HabilidadeId")
                        .HasColumnType("uuid");

                    b.HasKey("UsuarioId", "HabilidadeId");

                    b.HasIndex("HabilidadeId");

                    b.ToTable("usuarios_habilidades", (string)null);
                });

            modelBuilder.Entity("HubGruposEstudo.Domain.Entities.ConquistaUsuario", b =>
                {
                    b.HasOne("HubGruposEstudo.Domain.Entities.Conquista", "Conquista")
                        .WithMany()
                        .HasForeignKey("ConquistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HubGruposEstudo.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Conquistas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conquista");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HubGruposEstudo.Domain.Entities.Etapa", b =>
                {
                    b.HasOne("HubGruposEstudo.Domain.Entities.Trilha", "Trilha")
                        .WithMany("Etapas")
                        .HasForeignKey("TrilhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trilha");
                });

            modelBuilder.Entity("HubGruposEstudo.Domain.Entities.Inscricao", b =>
                {
                    b.HasOne("HubGruposEstudo.Domain.Entities.Trilha", "Trilha")
                        .WithMany()
                        .HasForeignKey("TrilhaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HubGruposEstudo.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Inscricoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trilha");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HubGruposEstudo.Domain.Entities.Trilha", b =>
                {
                    b.HasOne("HubGruposEstudo.Domain.Entities.Usuario", "Criador")
                        .WithMany("TrilhasCriadas")
                        .HasForeignKey("CriadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HubGruposEstudo.Domain.Entities.Habilidade", "Habilidade")
                        .WithMany()
                        .HasForeignKey("HabilidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Criador");

                    b.Navigation("Habilidade");
                });

            modelBuilder.Entity("HubGruposEstudo.Domain.Entities.Troca", b =>
                {
                    b.HasOne("HubGruposEstudo.Domain.Entities.Habilidade", "HabilidadeA")
                        .WithMany()
                        .HasForeignKey("HabilidadeAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HubGruposEstudo.Domain.Entities.Habilidade", "HabilidadeB")
                        .WithMany()
                        .HasForeignKey("HabilidadeBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HubGruposEstudo.Domain.Entities.Trilha", "TrilhaA")
                        .WithMany()
                        .HasForeignKey("TrilhaAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HubGruposEstudo.Domain.Entities.Trilha", "TrilhaB")
                        .WithMany()
                        .HasForeignKey("TrilhaBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HubGruposEstudo.Domain.Entities.Usuario", "UsuarioA")
                        .WithMany()
                        .HasForeignKey("UsuarioAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HubGruposEstudo.Domain.Entities.Usuario", "UsuarioB")
                        .WithMany()
                        .HasForeignKey("UsuarioBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HabilidadeA");

                    b.Navigation("HabilidadeB");

                    b.Navigation("TrilhaA");

                    b.Navigation("TrilhaB");

                    b.Navigation("UsuarioA");

                    b.Navigation("UsuarioB");
                });

            modelBuilder.Entity("HubGruposEstudo.Domain.Entities.UsuarioHabilidade", b =>
                {
                    b.HasOne("HubGruposEstudo.Domain.Entities.Habilidade", "Habilidade")
                        .WithMany()
                        .HasForeignKey("HabilidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HubGruposEstudo.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Habilidades")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidade");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HubGruposEstudo.Domain.Entities.Trilha", b =>
                {
                    b.Navigation("Etapas");
                });

            modelBuilder.Entity("HubGruposEstudo.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Conquistas");

                    b.Navigation("Habilidades");

                    b.Navigation("Inscricoes");

                    b.Navigation("TrilhasCriadas");
                });
#pragma warning restore 612, 618
        }
    }
}
